kafka_broker: "{{groups['processing-cluster-kafka'][0]}}:9092"

analytics:
   home: /mount/data/analytics
analytics_api:
   root: "{{ analytics.home }}/api"
   home: "{{ analytics.home }}/api/analytics-api-2.0"
   service_args: -Dconfig.file=/mount/data/analytics/api/{{ env }}.conf
   paths: ['/home/analytics/sbin', '/mount/data/analytics', '/mount/data/analytics/logs', '/mount/data/analytics/logs/services', '/mount/data/analytics/logs/api-service', '/mount/data/analytics/api', '/mount/data/analytics/tmp', '/mount/data/analytics/scripts/monitor-data']
cassandra:
  keyspace_prefix: "{{ env }}_"

geo_location_city: "{{ env }}_geo_location_city"
geo_location_city_ipv4: "{{ env }}_geo_location_city_ipv4"
report_config: "{{env}}_report_config"
default_channel_id: "in.ekstep"
consumer_channel_cache_type: ConsumerChannel
artifact_name: "analytics-api-2.0-dist.zip"

analytics: 
   home: /mount/data/analytics
