apiVersion: v1
kind: ConfigMap
metadata:
  name: telemetry-extractor-config
  namespace: {{ .Values.namespace }}
data:
  telemetry-extractor.conf: |
{{ .Values.telemetry-extractor-config | indent 4 }}